apiVersion: apps/v1
kind: Deployment
metadata:
  name: saletracker
spec:
  selector:
    matchLabels:
      app: saletracker
  replicas: 2
  template: # template for the pods
    metadata:
      name: saletracker
      labels:
        app: saletracker
    spec:
      containers:
      - name: saletracker
        image: semiscone/saletracker
